/**
 * Texte von Rechnung und Gutschrift in jeder Sprache der Rechnungs-API — eine
 * Quelle fuer das Backend (PDF, E-Rechnung, Mail) und das Web (Statusseite).
 * Das Backend liest sie aus `fixtures/rechnung-texte.json` (`npm run
 * fixtures:rechnungstexte`).
 *
 * Datum und Betraege stehen NICHT hier: sie bleiben in jeder Sprache
 * oesterreichisch formatiert (15.09.2026, € 1.234,56) und werden vom Aufrufer
 * eingesetzt. Platzhalter in {geschweiften} Klammern; jede Sprache hat dieselben
 * Schluessel und je Schluessel dieselben Platzhalter (test/rechnung-texte.test.ts).
 * Die Schluessel sind seit 1.0 englisch (alt und neu in
 * `fixtures/texte-umbenennung.json`), die Texte bleiben, wie sie sind.
 *
 * Steuerhinweise nennen in jeder Sprache die Gesetzesstelle — § 11 UStG verlangt
 * einen Hinweis, keinen Wortlaut; die Fundstelle macht ihn eindeutig.
 */
import type { InvoiceLanguage } from './vertrag.js';

const DE = {
  'pdf.title.invoice': 'RECHNUNG',
  'pdf.title.creditNote': 'GUTSCHRIFT',
  'pdf.badge.paid': 'BEZAHLT',
  'pdf.badge.directDebit': 'SEPA-LASTSCHRIFT',
  'pdf.meta.number.invoice': 'Rechnungsnr.',
  'pdf.meta.number.creditNote': 'Gutschriftsnr.',
  'pdf.meta.date.invoice': 'Rechnungsdatum',
  'pdf.meta.date.creditNote': 'Gutschriftsdatum',
  'pdf.meta.servicePeriod': 'Leistungszeitraum',
  'pdf.meta.dueDate': 'Fälligkeit',
  'pdf.reference.creditNote': 'Gutschrift zu Rechnung {nummer}',
  'pdf.reference.dated': ' vom {datum}',
  'pdf.label.invoice': 'Rechnung {nummer}',
  'pdf.label.creditNote': 'Gutschrift {nummer}',
  'pdf.vatId': 'UID: {uid}',
  'pdf.table.pos': 'POS',
  'pdf.table.description': 'BESCHREIBUNG',
  'pdf.table.quantity': 'MENGE',
  'pdf.table.vat': 'UST',
  'pdf.table.unitNet': 'EINZEL NETTO',
  'pdf.table.amountNet': 'BETRAG NETTO',
  'pdf.table.unitGross': 'EINZEL BRUTTO',
  'pdf.table.amountGross': 'BETRAG BRUTTO',
  'pdf.item.discount': 'abzüglich {prozent} % Rabatt',
  'pdf.totals.subtotal': 'Zwischensumme netto',
  'pdf.totals.vat': 'Umsatzsteuer {satz}%',
  'pdf.totals.includedVat': 'darin {satz}% USt von {netto} netto',
  'pdf.totals.grandTotal.invoice': 'Gesamtbetrag',
  'pdf.totals.grandTotal.creditNote': 'Gutschriftsbetrag',
  'tax.smallBusiness': 'Gemäß § 6 Abs. 1 Z 27 UStG wird keine Umsatzsteuer verrechnet (Kleinunternehmer).',
  'tax.intraCommunitySupply.title': 'Steuerfreie innergemeinschaftliche Lieferung. ',
  'tax.intraCommunitySupply.text':
    'Gemäß Art. 6 Abs. 1 UStG (Art. 138 MwSt-RL 2006/112/EG). Die Erwerbsbesteuerung erfolgt durch den Abnehmer im Bestimmungsland.',
  'tax.exportThirdCountry': 'Steuerfreie Ausfuhrlieferung (§ 6 Abs. 1 Z 1 UStG).',
  // Reverse Charge ist KEINE Steuerbefreiung: der Umsatz bleibt steuerpflichtig,
  // nur die Steuer schuldet der Empfaenger (§ 11 Abs. 1a UStG; der Begriff steht
  // wortgleich in Art. 226 Nr. 11a MwSt-RL). „Steuerfrei" waere sachlich falsch
  // und erbraechte den vorgeschriebenen Hinweis nicht.
  'tax.reverseCharge.title': 'Steuerschuldnerschaft des Leistungsempfängers. ',
  'tax.reverseCharge.text':
    'Übergang der Steuerschuld gem. Art. 196 MwSt-RL 2006/112/EG (innergemeinschaftliche Leistung). Die Leistung ist nicht steuerfrei — die Umsatzsteuer schuldet und entrichtet der Leistungsempfänger in seinem Land.',
  // Beide UID-Nummern: bei Reverse Charge § 11 Abs. 1a, bei der ig. Lieferung
  // Art. 11 Abs. 2 UStG.
  'tax.vatIdLine': 'UID Leistungserbringer: {verkaeufer}   ·   UID Leistungsempfänger: {kaeufer}',
  // Inlands-Reverse-Charge: je Grund ein Satz, der die Gesetzesstelle nennt —
  // sie traegt den Hinweis nach § 11 Abs. 1a UStG.
  'tax.rcReason.construction': 'Bauleistung gemäß § 19 Abs. 1a UStG.',
  'tax.rcReason.scrap': 'Schrott und Abfallstoffe gemäß Schrott-Umsatzsteuerverordnung (BGBl. II Nr. 129/2007).',
  'tax.rcReason.mobile_devices': 'Mobilfunkgeräte bzw. integrierte Schaltkreise gemäß § 19 Abs. 1e lit. b UStG.',
  'tax.rcReason.it_devices': 'Laptops, Tablets bzw. Videospielkonsolen gemäß § 2 Z 1 Umsatzsteuerbetrugsbekämpfungsverordnung (BGBl. II Nr. 369/2013).',
  'tax.rcReason.metals': 'Metalle gemäß § 2 Z 4 Umsatzsteuerbetrugsbekämpfungsverordnung.',
  'tax.rcReason.emission_certificates': 'Treibhausgasemissionszertifikate gemäß § 19 Abs. 1e lit. a UStG.',
  'tax.rcReason.gas_electricity': 'Lieferung von Gas oder Elektrizität an einen Wiederverkäufer gemäß § 2 Z 2 Umsatzsteuerbetrugsbekämpfungsverordnung.',
  'tax.rcReason.energy_certificates': 'Gas- und Elektrizitätszertifikate gemäß § 2 Z 3 Umsatzsteuerbetrugsbekämpfungsverordnung.',
  'tax.rcReason.investment_gold': 'Steuerpflichtige Lieferung von Anlagegold gemäß § 2 Z 5 Umsatzsteuerbetrugsbekämpfungsverordnung.',
  'tax.rcReason.security_transfer': 'Lieferung von Sicherungs- bzw. Vorbehaltseigentum gemäß § 19 Abs. 1b UStG.',
  'tax.rcReason.foreign_supplier': 'Leistung eines nicht im Inland ansässigen Unternehmers gemäß § 19 Abs. 1 zweiter Satz UStG.',
  'tax.domestic.text': 'Die Umsatzsteuer schuldet und entrichtet der Leistungsempfänger. Die Leistung ist nicht steuerfrei.',
  'tax.outsideScope.title': 'Nicht steuerbarer Umsatz. ',
  'tax.outsideScope.text': 'Der Leistungsort liegt gemäß § 3a Abs. 6 UStG im Ansässigkeitsstaat des Leistungsempfängers; in Österreich fällt keine Umsatzsteuer an.',
  'pdf.payment.title': 'ZAHLUNGSINFORMATIONEN',
  'pdf.payment.recipient': 'Empfänger',
  'pdf.payment.iban': 'IBAN',
  'pdf.payment.bic': 'BIC',
  'pdf.payment.paymentReference': 'Verwendungszweck',
  'pdf.payment.noteUntil': 'Zahlbar ohne Abzug bis {datum}. Vielen Dank für Ihren Auftrag.',
  'pdf.payment.note': 'Zahlbar ohne Abzug. Vielen Dank für Ihren Auftrag.',
  'pdf.payment.qr': 'Mit Banking-App scannen & zahlen',
  'pdf.paid.text': 'Diese Rechnung ist beglichen. Es ist nichts weiter zu tun.',
  'pdf.paid.date': 'Bezahlt am',
  'pdf.paid.paymentMethod': 'Zahlungsart',
  'paymentMethod.cash': 'Bar',
  'paymentMethod.transfer': 'Überweisung',
  'paymentMethod.card': 'Karte',
  'paymentMethod.online': 'Online',
  'pdf.directDebit.text': 'Der Betrag wird per SEPA-Lastschrift eingezogen. Sie müssen nichts veranlassen.',
  'pdf.directDebit.collectionDate': 'Einzug am',
  'pdf.directDebit.account': 'Konto',
  'pdf.directDebit.mandateReference': 'Mandatsreferenz',
  'pdf.directDebit.mandateDate': 'Mandat vom',
  'pdf.directDebit.warning': 'Bitte für Deckung sorgen — die Kosten einer Rücklastschrift werden weiterverrechnet.',
  'pdf.refund.text': 'Der Betrag wird auf dem ursprünglichen Zahlungsweg erstattet. Sie müssen nichts veranlassen.',
  'pdf.refund.reference': 'Bezug',
  'pdf.refund.amount': 'Erstattungsbetrag',
  'pdf.status.title': 'Zahlungsstatus online verfolgen',
  'pdf.status.text': 'Zahlung bzw. Einzug prüfen und Benachrichtigungen aktivieren.',
  'pdf.status.link': 'Link',
  'pdf.status.password': 'Passwort',
  'pdf.footer.contact': 'Kontakt',
  'pdf.footer.register': 'Register & Steuer',
  'pdf.footer.registeredOffice': 'Sitz: {ort}',
  'pdf.footer.note': 'Erstellt mit Kasseneck — ein Produkt der Kreiseck',
  'pdf.page': 'Seite {nummer} / {gesamt}',
  'country.AT': 'Österreich',
  'country.DE': 'Deutschland',
  'country.CH': 'Schweiz',
  'country.IT': 'Italien',
  'country.LI': 'Liechtenstein',
  'copy.invoice': 'Übersetzung – keine eigene Rechnung · Original: Rechnung Nr. {nummer} vom {datum}',
  'copy.creditNote': 'Übersetzung – keine eigene Gutschrift · Original: Gutschrift Nr. {nummer} vom {datum}',
  'creditNote.intro': 'Grund: {grund}',
  'creditNote.reason.cancellation': 'Stornierung',
  'creditNote.reason.price_reduction': 'Preisnachlass',
  'creditNote.reason.return': 'Rücksendung',
  'creditNote.reason.incorrect_invoice': 'Fehlerhafte Rechnung',
  'creditNote.reason.other': 'Sonstiges',
  'einvoice.exemption.reverseCharge': 'Steuerschuldnerschaft des Leistungsempfängers (Reverse Charge)',
  'einvoice.exemption.smallBusiness': 'Steuerbefreit — Kleinunternehmer gemäß §6 Abs. 1 Z 27 UStG',
  'einvoice.exemption.intraCommunitySupply': 'Steuerfreie innergemeinschaftliche Lieferung gemäß Art. 6 Abs. 1 UStG',
  'einvoice.exemption.outsideScope': 'Nicht steuerbarer Umsatz — Leistungsort im Ausland (§ 3a Abs. 6 UStG)',
  'einvoice.exemption.exportThirdCountry': 'Steuerfreie Ausfuhrlieferung gemäß §6 Abs. 1 Z 1 UStG',
  'einvoice.payableUntil': 'Zahlbar bis {datum}',
  'unit.piece': 'Stk',
  'unit.pair': 'Paar',
  'unit.set': 'Set',
  'unit.dozen': 'Dtzd.',
  'unit.second': 'Sek.',
  'unit.minute': 'Min.',
  'unit.hour': 'Std',
  'unit.day': 'Tag',
  'unit.night': 'Nacht',
  'unit.week': 'Woche',
  'unit.month': 'Monat',
  'unit.quarter': 'Quartal',
  'unit.half_year': 'Halbjahr',
  'unit.year': 'Jahr',
  'unit.milligram': 'mg',
  'unit.gram': 'g',
  'unit.kilogram': 'kg',
  'unit.tonne': 't',
  'unit.millimetre': 'mm',
  'unit.centimetre': 'cm',
  'unit.metre': 'm',
  'unit.running_metre': 'lfm',
  'unit.kilometre': 'km',
  'unit.square_metre': 'm²',
  'unit.hectare': 'ha',
  'unit.millilitre': 'ml',
  'unit.litre': 'l',
  'unit.cubic_metre': 'm³',
  'unit.kilowatt_hour': 'kWh',
  'unit.megawatt_hour': 'MWh',
  'unit.gigabyte': 'GB',
  'unit.terabyte': 'TB',
  'unit.flat_rate': 'Pauschal',
  'unit.person': 'Pers.',
  'unit.licence': 'Lizenz',
  'unit.user': 'Benutzer',
  'unit.device': 'Gerät',
  'unit.session': 'Sitzung',
  'unit.trip': 'Fahrt',
  'unit.page': 'Seite',
  'unit.sheet': 'Blatt',
  'unit.package': 'Pkg.',
  'unit.box': 'Box',
  'unit.carton': 'Karton',
  'unit.bottle': 'Fl.',
  'unit.can': 'Dose',
  'unit.roll': 'Rolle',
  'unit.bag': 'Sack',
  'unit.pallet': 'Palette',
  'unitName.piece': 'Stück',
  'unitName.pair': 'Paar',
  'unitName.set': 'Set',
  'unitName.dozen': 'Dutzend',
  'unitName.second': 'Sekunde',
  'unitName.minute': 'Minute',
  'unitName.hour': 'Stunde',
  'unitName.day': 'Tag',
  'unitName.night': 'Nacht',
  'unitName.week': 'Woche',
  'unitName.month': 'Monat',
  'unitName.quarter': 'Quartal',
  'unitName.half_year': 'Halbjahr',
  'unitName.year': 'Jahr',
  'unitName.milligram': 'Milligramm',
  'unitName.gram': 'Gramm',
  'unitName.kilogram': 'Kilogramm',
  'unitName.tonne': 'Tonne',
  'unitName.millimetre': 'Millimeter',
  'unitName.centimetre': 'Zentimeter',
  'unitName.metre': 'Meter',
  'unitName.running_metre': 'Laufmeter',
  'unitName.kilometre': 'Kilometer',
  'unitName.square_metre': 'Quadratmeter',
  'unitName.hectare': 'Hektar',
  'unitName.millilitre': 'Milliliter',
  'unitName.litre': 'Liter',
  'unitName.cubic_metre': 'Kubikmeter',
  'unitName.kilowatt_hour': 'Kilowattstunde',
  'unitName.megawatt_hour': 'Megawattstunde',
  'unitName.gigabyte': 'Gigabyte',
  'unitName.terabyte': 'Terabyte',
  'unitName.flat_rate': 'Pauschale',
  'unitName.person': 'Person',
  'unitName.licence': 'Lizenz',
  'unitName.user': 'Benutzer',
  'unitName.device': 'Gerät',
  'unitName.session': 'Sitzung',
  'unitName.trip': 'Fahrt',
  'unitName.page': 'Seite',
  'unitName.sheet': 'Blatt',
  'unitName.package': 'Packung',
  'unitName.box': 'Box',
  'unitName.carton': 'Karton',
  'unitName.bottle': 'Flasche',
  'unitName.can': 'Dose',
  'unitName.roll': 'Rolle',
  'unitName.bag': 'Sack',
  'unitName.pallet': 'Palette',
} as const;

export type InvoiceTextKey = keyof typeof DE;

const EN: Readonly<Record<InvoiceTextKey, string>> = {
  'pdf.title.invoice': 'INVOICE',
  'pdf.title.creditNote': 'CREDIT NOTE',
  'pdf.badge.paid': 'PAID',
  'pdf.badge.directDebit': 'SEPA DIRECT DEBIT',
  'pdf.meta.number.invoice': 'Invoice no.',
  'pdf.meta.number.creditNote': 'Credit note no.',
  'pdf.meta.date.invoice': 'Invoice date',
  'pdf.meta.date.creditNote': 'Credit note date',
  'pdf.meta.servicePeriod': 'Service period',
  'pdf.meta.dueDate': 'Due date',
  'pdf.reference.creditNote': 'Credit note for invoice {nummer}',
  'pdf.reference.dated': ' dated {datum}',
  'pdf.label.invoice': 'Invoice {nummer}',
  'pdf.label.creditNote': 'Credit note {nummer}',
  'pdf.vatId': 'VAT ID: {uid}',
  'pdf.table.pos': 'POS',
  'pdf.table.description': 'DESCRIPTION',
  'pdf.table.quantity': 'QTY',
  'pdf.table.vat': 'VAT',
  'pdf.table.unitNet': 'UNIT NET',
  'pdf.table.amountNet': 'AMOUNT NET',
  'pdf.table.unitGross': 'UNIT GROSS',
  'pdf.table.amountGross': 'AMOUNT GROSS',
  'pdf.item.discount': 'less {prozent}% discount',
  'pdf.totals.subtotal': 'Subtotal net',
  'pdf.totals.vat': 'VAT {satz}%',
  'pdf.totals.includedVat': 'incl. {satz}% VAT on {netto} net',
  'pdf.totals.grandTotal.invoice': 'Total',
  'pdf.totals.grandTotal.creditNote': 'Credit total',
  'tax.smallBusiness': 'No VAT charged pursuant to § 6 (1) no. 27 UStG (small business exemption).',
  'tax.intraCommunitySupply.title': 'VAT-exempt intra-Community supply. ',
  'tax.intraCommunitySupply.text':
    'Pursuant to Art. 6 (1) UStG (Art. 138 of VAT Directive 2006/112/EC). The acquisition is taxed by the customer in the country of destination.',
  'tax.exportThirdCountry': 'VAT-exempt export delivery (§ 6 (1) no. 1 UStG).',
  'tax.reverseCharge.title': 'Reverse charge – VAT liability of the recipient. ',
  'tax.reverseCharge.text':
    'VAT liability transferred pursuant to Art. 196 of VAT Directive 2006/112/EC (intra-Community service). The service is not VAT-exempt — the recipient owes and accounts for the VAT in their country.',
  'tax.vatIdLine': 'VAT ID supplier: {verkaeufer}   ·   VAT ID recipient: {kaeufer}',
  'tax.rcReason.construction': 'Construction work pursuant to § 19 (1a) UStG.',
  'tax.rcReason.scrap': 'Scrap and waste materials pursuant to the Austrian scrap VAT regulation (BGBl. II No. 129/2007).',
  'tax.rcReason.mobile_devices': 'Mobile phones or integrated circuits pursuant to § 19 (1e) (b) UStG.',
  'tax.rcReason.it_devices': 'Laptops, tablets or games consoles pursuant to § 2 no. 1 of the Austrian VAT anti-fraud regulation (BGBl. II No. 369/2013).',
  'tax.rcReason.metals': 'Metals pursuant to § 2 no. 4 of the Austrian VAT anti-fraud regulation.',
  'tax.rcReason.emission_certificates': 'Greenhouse gas emission allowances pursuant to § 19 (1e) (a) UStG.',
  'tax.rcReason.gas_electricity': 'Supply of gas or electricity to a reseller pursuant to § 2 no. 2 of the Austrian VAT anti-fraud regulation.',
  'tax.rcReason.energy_certificates': 'Gas and electricity certificates pursuant to § 2 no. 3 of the Austrian VAT anti-fraud regulation.',
  'tax.rcReason.investment_gold': 'Taxable supply of investment gold pursuant to § 2 no. 5 of the Austrian VAT anti-fraud regulation.',
  'tax.rcReason.security_transfer': 'Supply of goods under a security or retention of title arrangement pursuant to § 19 (1b) UStG.',
  'tax.rcReason.foreign_supplier': 'Supply by a business not established in Austria pursuant to § 19 (1) second sentence UStG.',
  'tax.domestic.text': 'The recipient owes and accounts for the VAT. The supply is not VAT-exempt.',
  'tax.outsideScope.title': 'Outside the scope of Austrian VAT. ',
  'tax.outsideScope.text': 'The place of supply is the recipient\'s country pursuant to § 3a (6) UStG; no Austrian VAT applies.',
  'pdf.payment.title': 'PAYMENT DETAILS',
  'pdf.payment.recipient': 'Payee',
  'pdf.payment.iban': 'IBAN',
  'pdf.payment.bic': 'BIC',
  'pdf.payment.paymentReference': 'Payment reference',
  'pdf.payment.noteUntil': 'Payable without deduction by {datum}. Thank you for your business.',
  'pdf.payment.note': 'Payable without deduction. Thank you for your business.',
  'pdf.payment.qr': 'Scan with your banking app to pay',
  'pdf.paid.text': 'This invoice has been paid. No further action is required.',
  'pdf.paid.date': 'Paid on',
  'pdf.paid.paymentMethod': 'Payment method',
  'paymentMethod.cash': 'Cash',
  'paymentMethod.transfer': 'Bank transfer',
  'paymentMethod.card': 'Card',
  'paymentMethod.online': 'Online',
  'pdf.directDebit.text': 'The amount will be collected by SEPA direct debit. No action is required on your part.',
  'pdf.directDebit.collectionDate': 'Collection date',
  'pdf.directDebit.account': 'Account',
  'pdf.directDebit.mandateReference': 'Mandate reference',
  'pdf.directDebit.mandateDate': 'Mandate date',
  'pdf.directDebit.warning': 'Please ensure sufficient funds — the costs of a returned direct debit will be charged to you.',
  'pdf.refund.text': 'The amount will be refunded via the original payment method. No action is required on your part.',
  'pdf.refund.reference': 'Reference',
  'pdf.refund.amount': 'Refund amount',
  'pdf.status.title': 'Track payment status online',
  'pdf.status.text': 'Check payment or direct debit status and turn on notifications.',
  'pdf.status.link': 'Link',
  'pdf.status.password': 'Password',
  'pdf.footer.contact': 'Contact',
  'pdf.footer.register': 'Registration & tax',
  'pdf.footer.registeredOffice': 'Registered office: {ort}',
  'pdf.footer.note': 'Created with Kasseneck — a Kreiseck product',
  'pdf.page': 'Page {nummer} / {gesamt}',
  'country.AT': 'Austria',
  'country.DE': 'Germany',
  'country.CH': 'Switzerland',
  'country.IT': 'Italy',
  'country.LI': 'Liechtenstein',
  'copy.invoice': 'Translation – not a separate invoice · Original: Invoice No. {nummer} dated {datum}',
  'copy.creditNote': 'Translation – not a separate credit note · Original: Credit note No. {nummer} dated {datum}',
  'creditNote.intro': 'Reason: {grund}',
  'creditNote.reason.cancellation': 'Cancellation',
  'creditNote.reason.price_reduction': 'Price reduction',
  'creditNote.reason.return': 'Return',
  'creditNote.reason.incorrect_invoice': 'Incorrect invoice',
  'creditNote.reason.other': 'Other',
  'einvoice.exemption.reverseCharge': 'Reverse charge – VAT liability of the recipient',
  'einvoice.exemption.smallBusiness': 'VAT exempt — small business pursuant to § 6 (1) no. 27 UStG',
  'einvoice.exemption.intraCommunitySupply': 'VAT-exempt intra-Community supply pursuant to Art. 6 (1) UStG',
  'einvoice.exemption.outsideScope': 'Outside the scope of VAT — place of supply abroad (§ 3a (6) UStG)',
  'einvoice.exemption.exportThirdCountry': 'VAT-exempt export delivery pursuant to § 6 (1) no. 1 UStG',
  'einvoice.payableUntil': 'Payable by {datum}',
  'unit.piece': 'pcs',
  'unit.pair': 'pair',
  'unit.set': 'set',
  'unit.dozen': 'doz.',
  'unit.second': 'sec',
  'unit.minute': 'min',
  'unit.hour': 'h',
  'unit.day': 'day',
  'unit.night': 'night',
  'unit.week': 'wk',
  'unit.month': 'mo',
  'unit.quarter': 'qtr',
  'unit.half_year': 'half-yr',
  'unit.year': 'yr',
  'unit.milligram': 'mg',
  'unit.gram': 'g',
  'unit.kilogram': 'kg',
  'unit.tonne': 't',
  'unit.millimetre': 'mm',
  'unit.centimetre': 'cm',
  'unit.metre': 'm',
  'unit.running_metre': 'rm',
  'unit.kilometre': 'km',
  'unit.square_metre': 'm²',
  'unit.hectare': 'ha',
  'unit.millilitre': 'ml',
  'unit.litre': 'l',
  'unit.cubic_metre': 'm³',
  'unit.kilowatt_hour': 'kWh',
  'unit.megawatt_hour': 'MWh',
  'unit.gigabyte': 'GB',
  'unit.terabyte': 'TB',
  'unit.flat_rate': 'flat',
  'unit.person': 'pers.',
  'unit.licence': 'licence',
  'unit.user': 'user',
  'unit.device': 'device',
  'unit.session': 'session',
  'unit.trip': 'trip',
  'unit.page': 'page',
  'unit.sheet': 'sheet',
  'unit.package': 'pkg',
  'unit.box': 'box',
  'unit.carton': 'ctn',
  'unit.bottle': 'btl',
  'unit.can': 'can',
  'unit.roll': 'roll',
  'unit.bag': 'bag',
  'unit.pallet': 'plt',
  'unitName.piece': 'piece',
  'unitName.pair': 'pair',
  'unitName.set': 'set',
  'unitName.dozen': 'dozen',
  'unitName.second': 'second',
  'unitName.minute': 'minute',
  'unitName.hour': 'hour',
  'unitName.day': 'day',
  'unitName.night': 'night',
  'unitName.week': 'week',
  'unitName.month': 'month',
  'unitName.quarter': 'quarter',
  'unitName.half_year': 'half year',
  'unitName.year': 'year',
  'unitName.milligram': 'milligram',
  'unitName.gram': 'gram',
  'unitName.kilogram': 'kilogram',
  'unitName.tonne': 'tonne',
  'unitName.millimetre': 'millimetre',
  'unitName.centimetre': 'centimetre',
  'unitName.metre': 'metre',
  'unitName.running_metre': 'running metre',
  'unitName.kilometre': 'kilometre',
  'unitName.square_metre': 'square metre',
  'unitName.hectare': 'hectare',
  'unitName.millilitre': 'millilitre',
  'unitName.litre': 'litre',
  'unitName.cubic_metre': 'cubic metre',
  'unitName.kilowatt_hour': 'kilowatt hour',
  'unitName.megawatt_hour': 'megawatt hour',
  'unitName.gigabyte': 'gigabyte',
  'unitName.terabyte': 'terabyte',
  'unitName.flat_rate': 'flat rate',
  'unitName.person': 'person',
  'unitName.licence': 'licence',
  'unitName.user': 'user',
  'unitName.device': 'device',
  'unitName.session': 'session',
  'unitName.trip': 'trip',
  'unitName.page': 'page',
  'unitName.sheet': 'sheet',
  'unitName.package': 'package',
  'unitName.box': 'box',
  'unitName.carton': 'carton',
  'unitName.bottle': 'bottle',
  'unitName.can': 'can',
  'unitName.roll': 'roll',
  'unitName.bag': 'bag',
  'unitName.pallet': 'pallet',
};

export const INVOICE_TEXTS: Readonly<Record<InvoiceLanguage, Readonly<Record<InvoiceTextKey, string>>>> =
  Object.freeze({ de: Object.freeze({ ...DE }), en: Object.freeze({ ...EN }) });

/** Ein Text der gewaehlten Sprache mit eingesetzten Werten; ein fehlender Wert ist ein Programmierfehler. */
export function invoiceText(
  sprache: InvoiceLanguage,
  schluessel: InvoiceTextKey,
  werte: Readonly<Record<string, string | number>> = {},
): string {
  return INVOICE_TEXTS[sprache][schluessel].replace(/\{([a-zA-Z]+)\}/g, (_voll, name: string) => {
    if (!(name in werte)) throw new Error(`invoiceText ${schluessel}: Wert {${name}} fehlt`);
    return String(werte[name]);
  });
}
