/**
 * `@kreiseck/kasseneck-api/inventory` – die Lager-API: Artikel, Standorte,
 * Bestand und Lagerprotokoll lesen, Konto-Webhooks verwalten und eingehende
 * Zustellungen pruefen (Backend Stufe 5a); Artikel anlegen und aendern,
 * Bestand buchen und Ware reservieren (Stufe 5b, seit 1.5.0);
 * Variantengruppen (Stufe 5c, seit 1.6.0).
 *
 * Ein eigener Unterpfad wie `invoice`: der `api_key` eines Kontos gehoert auf
 * einen **Server** (etwa das Backend eines Online-Shops) und soll nicht
 * versehentlich in ein Browser-Buendel wandern.
 *
 * Mengen in Tausendstel der Basiseinheit, Geld in Cent, Einkaufspreise in
 * Mikro-Euro; alles Ganzzahlen.
 */

export { createInventoryClient, type InventoryClient, type InventoryClientOptions } from './api.js';

export { inventoryKeyAuth, type InventoryKeyAuthOptions } from './auth.js';

export {
  isInventoryError,
  isInventoryErrorCode,
  inventoryErrorCode,
  inventoryFieldErrors,
  inventoryRetryAfterSec,
  inventoryShortfalls,
  isInventoryWarningCode,
  type InventoryApiErrorCode,
  type InventoryFieldError,
} from './fehler.js';

export {
  createWebhook,
  deleteWebhook,
  getArticle,
  getStock,
  iterateArticles,
  iterateStock,
  iterateStockMovements,
  listArticles,
  listLocations,
  listStock,
  listStockMovements,
  listWebhookDeliveries,
  listWebhooks,
  lookupArticleByCode,
  rotateWebhookSecret,
  sendWebhookTest,
  updateWebhook,
} from './endpunkte.js';

export {
  changeStockCondition,
  createArticle,
  createReservation,
  deactivateArticle,
  extendReservation,
  getReservation,
  iterateReservations,
  listReservations,
  previewGoodsReceipt,
  receiveGoods,
  recordStockLoss,
  releaseReservation,
  reverseStockMovement,
  transferStock,
  updateArticle,
} from './schreiben.js';

export {
  addVariant,
  createVariantGroup,
  getVariantGroup,
  iterateVariantGroups,
  listVariantGroups,
  updateVariantGroup,
} from './varianten.js';

export {
  verifyInventoryWebhookSignature,
  parseInventoryWebhookEvent,
  WEBHOOK_SIGNATURE_HEADER,
  WEBHOOK_EVENT_HEADER,
  WEBHOOK_DELIVERY_HEADER,
  WEBHOOK_TOLERANCE_SEC,
  type VerifyInventoryWebhookOptions,
} from './webhook.js';

export type {
  AddVariantRequest,
  Article,
  ArticleInput,
  ArticleListQuery,
  ArticleLookup,
  ArticlePage,
  ChangeStockConditionRequest,
  CreateArticleRequest,
  CreateInventoryWebhookOptions,
  CreateReservationRequest,
  CreateVariantGroupRequest,
  DeactivateArticleRequest,
  ExtendReservationRequest,
  GoodsReceiptItem,
  GoodsReceiptPreview,
  GoodsReceiptPreviewLine,
  GoodsReceiptPreviewRequest,
  InventoryShortfall,
  InventoryWarning,
  InventoryWebhook,
  InventoryWebhookDelivery,
  InventoryWebhookEnvelope,
  InventoryWebhookEvent,
  InventoryWebhookList,
  InventoryWebhookPatch,
  InventoryWebhookTestDelivery,
  InventoryWebhookTestResult,
  InventoryWebhookWithSecret,
  LandedCost,
  Location,
  LocationAddress,
  ReceiveGoodsRequest,
  RecordStockLossRequest,
  ReleaseReservationItem,
  ReleaseReservationRequest,
  Reservation,
  ReservationItem,
  ReservationItemInput,
  ReservationListQuery,
  ReservationPage,
  ReverseStockMovementRequest,
  StockBelowMinimumEventData,
  StockChangedEventData,
  StockItem,
  StockLevel,
  StockListQuery,
  StockMovement,
  StockMovementLot,
  StockMovementPage,
  StockMovementQuery,
  StockMovementSourceRef,
  StockOperation,
  StockPage,
  StockResult,
  StockValue,
  TransferStockRequest,
  UpdateArticleRequest,
  UpdateVariantGroupRequest,
  VariantAttribute,
  VariantGroup,
  VariantGroupDefaults,
  VariantGroupDefaultsInput,
  VariantGroupListQuery,
  VariantGroupMember,
  VariantGroupPage,
  VariantInput,
} from './typen.js';

export {
  INVENTORY_ENDPOINTS,
  INVENTORY_ERROR_CODES,
  INVENTORY_REQUEST_ERROR_CODES,
  INVENTORY_WEBHOOK_EVENTS,
  INVENTORY_WEBHOOK_ENVELOPE_FIELDS,
  INVENTORY_WEBHOOK_LIMIT,
  INVENTORY_LIST_LIMIT_MAX,
  LOCATION_TYPES,
  STOCK_MOVEMENT_TYPES,
  STOCK_MOVEMENT_SOURCES,
  STOCK_CONDITIONS,
  STOCK_CHANGE_CAUSES,
  WEBHOOK_DELIVERY_STATUSES,
  INVENTORY_WARNING_CODES,
  STOCK_KINDS,
  STOCK_LOSS_REASONS,
  WITHDRAWAL_TYPES,
  LANDED_COST_TYPES,
  LANDED_COST_ALLOCATIONS,
  RESERVATION_STATUSES,
  INVENTORY_IDEMPOTENCY_KEY_MAX,
  RESERVATION_MINUTES_MIN,
  RESERVATION_MINUTES_MAX,
  VARIANT_ATTRIBUTES_MAX,
  VARIANT_VALUES_MAX,
  VARIANT_MATRIX_MAX,
  VARIANT_GROUP_ACTIVE_MAX,
  type InventoryEndpoint,
  type InventoryErrorCode,
  type InventoryRequestErrorCode,
  type InventoryWebhookEventType,
  type LocationType,
  type StockMovementType,
  type StockMovementSource,
  type StockCondition,
  type StockChangeCause,
  type WebhookDeliveryStatus,
  type InventoryWarningCode,
  type StockKind,
  type StockLossReason,
  type WithdrawalType,
  type LandedCostType,
  type LandedCostAllocation,
  type ReservationStatus,
} from './vertrag.js';
